<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-4JORBA0" failures="2" tests="3" name="Vision_ETL_v1.ETL_General" time="44.762" errors="0" timestamp="2024-09-05T16:03:21 IST" skipped="0">
  <testcase classname="Vision_ETL_v1.ETL_General" name="ETL_DC_001" time="14.213">
    <failure message="Login should fail for username &#039;RA&#039; with password &#039;vision@123&#039;." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Login should fail for username 'RA' with password 'vision@123'.
at org.testng.Assert.fail(Assert.java:99)
at Vision_ETL_v1.ETL_General.ETL_DC_001(ETL_General.java:88)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- ETL_DC_001 -->
  <system-out/>
  <testcase classname="Vision_ETL_v1.ETL_General" name="ETL_DC_001" time="12.359"/>
  <system-out/>
  <testcase classname="Vision_ETL_v1.ETL_General" name="ETL_DC_001" time="18.190">
    <failure message="Login should fail for username &#039;QW&#039; with password &#039;Vision@123&#039;." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Login should fail for username 'QW' with password 'Vision@123'.
at org.testng.Assert.fail(Assert.java:99)
at Vision_ETL_v1.ETL_General.ETL_DC_001(ETL_General.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- ETL_DC_001 -->
  <system-out/>
</testsuite> <!-- Vision_ETL_v1.ETL_General -->
